# =============================================================================
# Version
# =============================================================================
[version]
gstate_processed_schema = "1"
gstate_memory_schema = "1.16.2"

# =============================================================================
# Model
# =============================================================================
[model]
d_model = 256

[model.vision]
output_features = 512
weights_name = "DEFAULT"

[model.temporal]
hidden_features = 512
num_layers = 2
dropout = 0.1

[model.game_state]

[model.fusion]
output_features = 512

[model.controller]
button_outputs = 14

# =============================================================================
# Training hyperparameters
# =============================================================================

[training.hyperparameters]
sequence_length = 120
epochs = 20
learning_rate = 0.0001
weight_decay = 0.0001
use_amp = true
gradient_clip_norm = 1.0

[training.hyperparameters.controller_weights]
south = 1.0
east = 1.0
west = 1.0
north = 1.0
left_bumper = 1.0
right_bumper = 1.0
left_stick = 1.0
right_stick = 1.0

left_x = 1.0
left_y = 1.0
right_x = 1.0
right_y = 1.0

dpad_up = 1.0
dpad_down = 1.0
dpad_left = 1.0
dpad_right = 1.0
start = 1.0
back = 1.0

left_trigger = 1.0
right_trigger = 1.0

[training.hyperparameters.early_stopping]
enabled = true
patience = 3
min_delta = 0.001

[training.data_loader]
# (toml doesnt support None values so commented = none)
# batch_size 
shuffle = false
num_workers = 0
pin_memory = false

# =============================================================================
# Paths
# =============================================================================

[paths]
artifacts = "artifacts"
training_recordings = "recordings/train"
validation_recordings = "recordings/val"

# =============================================================================
# Data
# =============================================================================

[data.transforms.frames]
width = 480
height = 270
scale = true

[data.transforms.controller]
clamp_sticks = true
clamp_triggers = true

[data.stores.frames]
device = "cuda"
dimension_order = "NCHW" # ResNet expects NCHW
seek_mode = "exact"
num_ffmpeg_threads = 4

# =============================================================================
# Recording
# =============================================================================

[recording.files]
version = 1
video_file = "frames.mp4"
controller_file = "inputs.parquet"
game_state_file = "game_state.parquet"
metadata_file = "metadata.json"

[recording.video]
width = 1280
height = 720
fps = 30

[recording.controller]
flush_every = 1024

[recording.game_state]
flush_every = 1024
compression = "zstd"


# =============================================================================
# Logging
# =============================================================================

[logging.regular]
enabled = false
level = "INFO"
log_file_enable = false
name = "mimic_tear"
log_file = "logs/mimic_tear.log"

[logging.perf_logger]
enabled = true
level = "DEBUG"
log_file_enable = false
name = "mimic_tear.performance"
log_file = "logs/mimic_tear_perf.log"

[logging.grace]
enabled = true
level = "DEBUG"
log_file_enable = true
name = "mimic_tear.grace"
log_file = "logs/mimic_tear_grace.log"

[logging.profiling]
enabled = true
timer_enabled = true
cpu_enabled = true
ram_enabled = true
cuda_enabled = true

[logging.profiling.timer]
unit = "ms"
precision = 2

[logging.profiling.cpu]
cpu_percent = true

[logging.profiling.ram]
usage = true
delta = true

[logging.profiling.cuda]
allocated = true
reserved = false
peak = true

# =============================================================================
# Capture
# =============================================================================

[capture.screen]
gpu_index = 0
monitor_index = 0

[capture.gamepad]
stick_deadzone = 0.12

# =============================================================================
# Function profiles
# =============================================================================

[logging.profiling.profiles."Trainer.train_epoch"]
enabled = true
timer = true
cuda_timer = true
cpu = true
ram = true
cuda = true
aggregate = false
flush = true

[logging.profiling.profiles."Trainer.validate"]
enabled = true
timer = true
cuda_timer = true
cpu = true
ram = true
cuda = true
aggregate = false
flush = true

[logging.profiling.profiles."SequenceDataset.__getitem__"]
enabled = false
timer = true
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."TensorFrameStore.get"]
enabled = false
timer = true
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."FramesDataset.get_range"]
enabled = false
timer = true
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."TensorFrameStore.get_range"]
enabled = false
timer = true
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."EldenRingPolicy.forward"]
enabled = false
timer = true
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."PolicyLoss.forward"]
enabled = false
timer = true
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."Vision.forward"]
enabled = false
timer = false
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."Temporal.forward"]
enabled = false
timer = false
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."GameState.forward"]
enabled = false
timer = false
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."Fusion.forward"]
enabled = false
timer = false
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."Controller.forward"]
enabled = false
timer = false
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false
