# =============================================================================
# Version
# =============================================================================
[version]
gstate_tensor_schema = "2"
gstate_memory_schema = "1.16.2"
controller_tensor_schema = "2"

# =============================================================================
# Policy
# =============================================================================
[policy]
preset = "resnet_lstm"

[policy.vision]
type = "resnet18"
output_size = 512
weights_name = "DEFAULT"

[policy.game_state]
d_model = 256
aggregator = { type = "mean" }

[policy.fusion]
type = "concat"
output_size = 512

[policy.temporal]
type = "lstm"
hidden_size = 512
num_layers = 2
dropout = 0.1

# [policy.temporal]
# type = "transformer"
# d_model = 256
# num_layers = 4
# num_heads = 8
# window = 30
# dropout = 0.1

[policy.controller]
type = "gamepad"
num_buttons = 14

# =============================================================================
# Training hyperparameters
# =============================================================================

[training]
save_predictions = true
seed = 0
repeats = 1

[training.hyperparameters]
sequence_length = 120
epochs = 20
learning_rate = 0.0001
weight_decay = 0.0001
use_amp = true
gradient_clip_norm = 1.0
button_threshold = 0.5
analog_gain = 1.0

[training.hyperparameters.controller_weights]
south = 1.0
east = 5.0
west = 1.0
north = 1.0
left_bumper = 1.0
right_bumper = 10.0
left_stick = 1.0
right_stick = 15.0

left_x = 1.0
left_y = 1.0
right_x = 1.0
right_y = 1.0

dpad_up = 1.0
dpad_down = 1.0
dpad_left = 1.0
dpad_right = 1.0
start = 1.0
back = 1.0

left_trigger = 1.0
right_trigger = 1.0

[training.hyperparameters.early_stopping]
enabled = true
patience = 5
min_delta = 0.001

[training.data_loader]
# (toml doesnt support None values so commented = none)
# batch_size 
shuffle = false
num_workers = 0
pin_memory = false

# =============================================================================
# Paths
# =============================================================================

[paths]
artifacts = "artifacts"
training_recordings = "recordings/train"
validation_recordings = "recordings/val"

# =============================================================================
# Data
# =============================================================================

[data.transforms.frames]
width = 480
height = 270
scale = true

[data.transforms.controller]
clamp_sticks = true
clamp_triggers = true

[data.stores.frames]
device = "cuda"
dimension_order = "NCHW" # ResNet expects NCHW
seek_mode = "exact"
num_ffmpeg_threads = 4

# =============================================================================
# Recording
# =============================================================================

[recording.files]
version = 1
video_file = "frames.mp4"
controller_file = "inputs.parquet"
game_state_file = "game_state.parquet"
metadata_file = "metadata.json"

[recording.video]
width = 1280
height = 720
fps = 30

[recording.controller]
flush_every = 1024

[recording.game_state]
flush_every = 1024
compression = "zstd"


# =============================================================================
# Logging
# =============================================================================

[logging.regular]
enabled = false
level = "INFO"
log_file_enable = false
name = "mimic_tear"
log_file = "logs/mimic_tear.log"

[logging.perf_logger]
enabled = true
level = "DEBUG"
log_file_enable = false
name = "mimic_tear.performance"
log_file = "logs/mimic_tear_perf.log"

[logging.grace]
enabled = false
level = "DEBUG"
log_file_enable = true
name = "mimic_tear.grace"
log_file = "logs/mimic_tear_grace.log"

[logging.profiling]
enabled = true
timer_enabled = true
cpu_enabled = true
ram_enabled = true
cuda_enabled = true

[logging.profiling.timer]
unit = "ms"
precision = 2

[logging.profiling.cpu]
cpu_percent = true

[logging.profiling.ram]
usage = true
delta = true

[logging.profiling.cuda]
allocated = true
reserved = false
peak = true

# =============================================================================
# Capture
# =============================================================================

[capture.screen]
gpu_index = 0
monitor_index = 0

[capture.gamepad]
stick_deadzone = 0.12

# =============================================================================
# Function profiles
# =============================================================================

[logging.profiling.profiles."Trainer.train_epoch"]
enabled = true
timer = true
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = false
flush = true

[logging.profiling.profiles."Trainer.validate"]
enabled = true
timer = true
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = false
flush = true

[logging.profiling.profiles."SequenceDataset.__getitem__"]
enabled = true
timer = true
cuda_timer = false
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."ParquetStore.get_range"]
enabled = true
timer = true
cuda_timer = false
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."TensorDataset.get_range"]
enabled = false
timer = true
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."VideoStore.get_range"]
enabled = true
timer = true
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."DataPipeline.prepare_recordings"]
enabled = false
timer = true
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."Process.process_sequence"]
enabled = true
timer = true
cuda_timer = false
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."Policy.forward"]
enabled = true
timer = false
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."GamepadLoss.forward"]
enabled = false
timer = true
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false

[logging.profiling.profiles."ResNet18.forward"]
enabled = true
timer = false
cuda_timer = true
cpu = false
ram = false
cuda = false
aggregate = true
flush = false
