
# =============================================================================
# Paths
# =============================================================================

[paths]
artifacts = "artifacts"
training_recordings = "recordings/train"
validation_recordings = "recordings/val"

# =============================================================================
# Logging
# =============================================================================

[logging.regular]
enabled = true
level = "DEBUG"
log_file_enable = false
name = "mimic_tear"
log_file = "logs/mimic_tear.log"

[logging.perf_logger]
enabled = true
level = "DEBUG"
log_file_enable = false
name = "mimic_tear.performance"
log_file = "logs/mimic_tear_perf.log"


# =============================================================================
# Function profiles
# =============================================================================

[logging.profiling.profiles."Trainer.train_epoch"]
enabled = true

[logging.profiling.profiles."Trainer.validate"]
enabled = true

[logging.profiling.profiles."SequenceDataset.__getitem__"]
enabled = false

[logging.profiling.profiles."DataPipeline.prepare_recordings"]
enabled = false

[logging.profiling.profiles."Process.process_sequence"]
enabled = false

[logging.profiling.profiles."ParquetStore.get_range"]
enabled = false

[logging.profiling.profiles."TensorDataset.get_range"]
enabled = false

[logging.profiling.profiles."VideoStore.get_range"]
enabled = false

[logging.profiling.profiles."LSTMPolicy.forward"]
enabled = false

[logging.profiling.profiles."PolicyLoss.forward"]
enabled = false

[logging.profiling.profiles."Vision.forward"]
enabled = false

[logging.profiling.profiles."Temporal.forward"]
enabled = false

[logging.profiling.profiles."GameState.forward"]
enabled = false

[logging.profiling.profiles."Fusion.forward"]
enabled = false

[logging.profiling.profiles."Controller.forward"]
enabled = false
